2025-06-03 12:37:33,025 - trading.utils.error_handling - ERROR - Unexpected error in generate_explanation: ExplanationEngine.generate_explanation() takes 3 positional arguments but 4 were given
2025-06-03 12:37:33,028 - trading.utils.error_handling - ERROR - Traceback (most recent call last):
  File "C:\Users\Thomas\OneDrive\Desktop\Dashboard\evolve_clean\trading\utils\error_handling.py", line 114, in wrapper
    return func(*args, **kwargs)
TypeError: ExplanationEngine.generate_explanation() takes 3 positional arguments but 4 were given

2025-06-03 12:37:38,199 - trading.utils.error_handling - ERROR - Unexpected error in generate_explanation: ExplanationEngine.generate_explanation() takes 3 positional arguments but 4 were given
2025-06-03 12:37:38,200 - trading.utils.error_handling - ERROR - Traceback (most recent call last):
  File "C:\Users\Thomas\OneDrive\Desktop\Dashboard\evolve_clean\trading\utils\error_handling.py", line 114, in wrapper
    return func(*args, **kwargs)
TypeError: ExplanationEngine.generate_explanation() takes 3 positional arguments but 4 were given

